### ISSUE TITLE
Error parsing an NtExecutable into NtExecutableResource

### ISSUE THREAD

**Issue by DustinBrett** [jet2jet/resedit-js#29]
I've ran into an issue trying to get the icon from `iconsext.exe` (https://www.nirsoft.net/utils/iconsext.html). It gives me an error when passing the `NtExecutable` into `ResEdit.NtExecutableResource.from`. My usage [extractExeIcon()](https://github.com/DustinBrett/daedalOS/blob/main/components/system/Files/FileEntry/exeIcons.ts#L40). Windows 10 is able to parse this icon and the program works. In general this code works, but this `exe` specifically wasn't working.

![image](https://user-images.githubusercontent.com/16656318/166733146-99d379ed-939b-4e77-94c5-693c226faa52.png)

I am wondering if anyone has an idea why this might be happening?

Thanks for any help!

**Comment by jet2jet** [comment]
Thanks for the report.
I checked `iconsext.exe`, and it contains unusual offset data (RVA) in resource directory table. (FYI: perhaps due to this, ResourceHacker also fails to parse resources.)
There seem to be 'usual' offset data, including data referring icon resources, so we can pick up those resources by bypassing unusual offset data.

I'll work for this pattern.

**Comment by DustinBrett** [comment]
Thanks for the quick response and looking into it. Your project is much appreciated as I've had trouble finding a good JS resource editor that can run browser side and extract icons properly from exe's.

![image](https://user-images.githubusercontent.com/16656318/166974149-6a69eb73-55a5-4eb0-b634-6eee44ec80d7.png)

I figured you might want to know about this as Windows 10 managed to parse it and show an icon which made me think this could be valid or at least there was a way to handle these files.

**Comment by jet2jet** [comment]
I published [pe-library@0.3.0](https://www.npmjs.com/package/pe-library) and [resedit@1.6.0](https://www.npmjs.com/package/resedit) to support those resource data.
When using `NtExecutableResource.from`, please specify `true` to second parameter `ignoreUnparsableData`.

**Comment by DustinBrett** [comment]
Awesome! That did it! Thanks so much for looking into this and the fast response.

![image](https://user-images.githubusercontent.com/16656318/167163568-531a9e33-dd12-4cb8-80a3-0a6ebf4bcc2e.png)
