### ISSUE TITLE
Support ESM loading

### ISSUE THREAD

**Issue by Kruithne** [jet2jet/resedit-js#34]
Hey,

Thanks for creating this project. I'm looking to integrate this into a build process which uses ESM to import modules. You're already bundling an ESM version which works for type-hinting and bundling, but when importing directly into a non-bundled build script, the following error is thrown.

`Syntax Error: Cannot use import statement outside a module`

The modern way to resolve this is to set `"type": "module"` in `package.json`, which would need to be done for `pe-library` as well as `resedit-js`. I was going to make a quick PR, but I'm not sure how setting that property would work with how this project is built, but it would be great to get this working with ESM.

I noticed the use of `"module": "./dist/_esm/index.js",` but this is unfortunately non-standard and not used by Node.js, only by bundlers, so the error is thrown regardless.

https://nodejs.org/api/packages.html#type
https://nodejs.org/api/esm.html#esm_enabling

Thanks!

**Comment by jet2jet** [comment]
I released v1.7.0 to support ESM for Node.js.  
(This support will load CJS from ESM entrypoint due to the compatibility. In the next major version release the package will provide native ESM entrypoint. #35 )

Please confirm if you can use from ESM.

**Comment by Kruithne** [comment]
It appears that importing directly into a non-bundled ESM is now working without issues as of `1.7.0`. Thanks for the quick resolution, much appreciated!

**Comment by jet2jet** [comment]
Thanks for the confirmation. I'll close this issue.
