### ISSUE TITLE
Saving bitmap icon to file

### ISSUE THREAD

**Issue by yassine-cc** [jet2jet/resedit-js#44]
I've been trying to use this library to extract executable icons.
for `RawIconItem` types (png) i do the following:
- convert `resource.bin`  from `arraybuffer` to `array`
- dump the buffer to a file with a `.png` extension

But when i try to dump a resource of type `IconItem` (bitmap), i encounter issues where the resulting file seems corrupted, here is what i tried:
- run `resource.generate()`
- convert the `array buffer` to a `buffer`
- dump it into  a file with a `.ico` extension or `.bmp` extension

What am i missing?

**Comment by jet2jet** [comment]
Sorry at the lack of explanation.  
To save icons as `.ico` file, you need to use `IconFile` class.  
The following code is the sample TypeScript code for saving:

```ts
// `RE` is a namespace of resedit (`import * as RE from 'resedit'`)
// `res` is an instance of NtExecutableResource

// Load all icon groups
const iconEntries = RE.Resource.IconGroupEntry.fromEntries(res.entries);
// Extract all icon data for the first icon group
const icons = iconEntries[0].getIconItemsFromEntries(res.entries);
// Create a new IconFileItem instance
const iconFile = new RE.Data.IconFile();
// Set icons for the file (converting `IconItem` to `IconFileItem`)
iconFile.icons = icons.map((icon): RE.Data.IconFileItem => ({ data: icon }))
// Generate icon file binary
const bin = iconFile.generate();
// Save as .ico file
fs.writeFileSync('test.ico', Buffer.from(bin));
```

Note that resedit does not have a feature for saving data as `.bmp` file.  
At least it is necessary to append `BITMAPFILEHEADER` binary before the binary returned by `IconItem.generate()`.  
(For details please search for the Windows Bitmap File format.)

**Comment by yassine-cc** [comment]
Thank you, i appreciate the rapid response, that was extremely helpful

**Comment by jet2jet** [comment]
Closing this issue.  
Feel free to reopen if there are any more questions.
