### ISSUE TITLE
Could not extract icon notepad.exe

### ISSUE THREAD

**Issue by chan-hancom-com** [jet2jet/resedit-js#47]
I want to extract the icon for an exe file.
However, I cannot extract the icon for C:\Windows\System32\notepad.exe.

Here's my code.

```typescript
  public static async getFileIcon(path:string, index:number|undefined): Promise<string | undefined> {
    const resEdit = await load();
    const binary = await fs.readFile(path);
    const ex = resEdit.NtExecutable.from( binary, { ignoreCert: true});
    const exRes = resEdit.NtExecutableResource.from(ex, true);
    const iconEntries = resEdit.Resource.IconGroupEntry.fromEntries(exRes.entries);  // iconEntries is  empty array.
    for ( let i = 0 ; i < iconEntries.length ; i++ ) {
      const entry = iconEntries[i];
      const iconItems = entry.getIconItemsFromEntries(exRes.entries);
      for ( let j = 0 ; j < iconItems.length ; j ++ ) {
        const iconGroupItem = iconItems[j];
        if ( iconGroupItem instanceof resEdit.Data.RawIconItem ) {
          const base64 = Buffer.from(iconGroupItem.bin).toString('base64');
          return `data:image/png;base64,${base64}`;
        }
      }
    }
```

one more.
How can i get icon in c:\windows\system32\shell32.dll.

Thanks for the great library.

**Comment by jet2jet** [comment]
In Windows 10, `C:\Windows\System32\notepad.exe` has few resource data. To extract icons, please load `C:\Windows\SystemResources\notepad.exe.mun` as an NtExecutable.  
(I could not find information about .mun files, but from Windows 10 resource data for Windows applications seem to be stored in `C:\Windows\SystemResources\*.mun` files and `C:\Windows\System32\<locale>\*.mui` files.)  
Similarly, to load shell32 icons, please load `C:\Windows\SystemResources\shell32.dll.mun`.

**Comment by chan-hancom-com** [comment]
Thanks to the solution you provided, I was able to overcome them. I truly appreciate it. 
I wanted to express my sincere gratitude for taking the time to help. 
Looking forward to more of your great work!
