### ISSUE TITLE
Linux Environment Compatibility

### ISSUE THREAD

**Issue by refringe** [jet2jet/resedit-js#50]
Less of an issue and more a general question... Should this library allow for modifications to be done to EXE files within a Linux environment or does it rely on the Windows API to facilitate the changes?

Thank you for your time.

**Comment by jet2jet** [comment]
This library doesn't rely on the Windows API (and Node.js API), so the library should work on the Linux environment.  
If you encounter an issue, feel free to report the issue.

**Comment by refringe** [comment]
Thank you for confirming.
