### ISSUE TITLE
Start offset outside bounds of the buffer with executabled built by pkg

### ISSUE THREAD

**Issue by haakonnessjoen** [jet2jet/resedit-js#58]
I am using `@yao-pkg/pkg` to build a node22 executable with source files and assets all included in the executable.
When I try to load the resulting exe file with `const exe = ResEdit.NtExecutable.from(fs.readFileSync(exefile))`, it fails with the following error:
```
RangeError: Start offset 1869489988 is outside the bounds of the buffer
    at new DataView (<anonymous>)
    at createDataView (file://node_modules/pe-library/dist/util/functions.js:23:16)
    at ImageNtHeaders.from (file://node_modules/pe-library/dist/format/ImageNtHeaders.js:29:21)
    at NtExecutable.from (file://node_modules/pe-library/dist/NtExecutable.js:52:33)
```

But the executable file is only 109190440 bytes long. So it seems to miscalculate the offset from some header, or pkg writes an invalid header that windows somehow doesn't get angry at?

Resource hacker also has no problem opening the exe file and listing resources from it.

I have no way of knowing if this is an issue with jet2jet/pe-library or @yao-pkg/pkg, but since neither windows or resource hacker has problems with the file, i think it might be resedit/pe-library

**Comment by haakonnessjoen** [comment]
I've also tried it directly on the node binaries fetched by @yao-pkg/pkg-fetch, and the exact same error occurs

**Comment by jet2jet** [comment]
Thanks for the report.  
Can you attach the EXE file here? I want to reproduce and investigate the problem.

**Comment by haakonnessjoen** [comment]
Hah, I just realized that it was because of a rather embarrassing error of mine. I created a script "update-icon.mjs", that was reading the exe file specified from the command line, but I forgot to use argv index + 1. So the tool tried to give it's own .mjs file instead of the exe file to your function. So no wonder it didn't understand it...

Maybe you could add a check for the MZ header to put idiots like me in the correct direction 😇 

Sorry for the false issue!
