### ISSUE TITLE
Code signature size and offset preserved but content is not

### ISSUE THREAD

**Issue by AlexanderOMara** [jet2jet/resedit-js#9]
Here's a Gist which takes a signed exe, reads it in, and writes it out again.

https://gist.github.com/AlexanderOMara/f14a4ba62a2432a1bb3a96f1de541c98

Apart from the checksum (fixed in another issue, but not published to NPM yet) the only difference is that the code signature data at the end it not preserved, though the headers says it has been (the entry is `ImageDirectoryEntry.Security` in `resedit-js`).

<img width="1192" alt="Screen Shot 2019-12-03 at 5 27 16 PM" src="https://user-images.githubusercontent.com/1740229/70095211-2ed1ed00-15f2-11ea-9b0a-4cd80632bcf9.png">

A quick note on how the code signature works, the code signature is simply at the end of the file, with the Security entry specifying the file offset and size of the data (not the virtual address).

In order to achieve feature parity with rcedit, I started to try to implement a way to preserve this data, but it looks like it requires some restructuring to do this, and I wasn't sure how best to go about refactoring this.

With some direction, I could probably create a pull request.

**Comment by jet2jet** [comment]
I checked some signed executable binaries and found that `VirtualAddress` of `IMAGE_DATA_DIRECTORY` for the Security table (a.k.a. 'Certificate table') is not the RVA, but the physical address.  
And I finally found that this behavior is described in the following section:  
https://docs.microsoft.com/ja-jp/windows/win32/debug/pe-format#the-attribute-certificate-table-image-only

> The virtual address value from the Certificate Table entry in the Optional Header Data Directory is **a file offset** to the first attribute certificate entry.

(...although `VirtualAddress` is described as 'RVA' in [this section](https://docs.microsoft.com/ja-jp/windows/win32/debug/pe-format#optional-header-data-directories-image-only)...)

\# I tested and found that Imagehlp API `ImageDirectoryEntryToDataEx` does not handle this properly, and returns weird data block.

To fix this, resedit-js can handle specially for the Security table (treat `VirtualAddress` as a physical address). But I think that `NtExecutable.from` should throw a 'Not supported' error if the executable contains the Security table (unless resedit-js has re-signing process for executables, which is not easy to implement / refs. https://stackoverflow.com/questions/57151382/manually-sign-a-pe-file).

\# Removing the Security table (= stripping certificates/signs) is an alternative and might be better for expert users.

**Comment by AlexanderOMara** [comment]
Currently resedit-js doesn't read the data at all, because it's not in a section which `ImageSectionHeaderArray` would read.

Removing the signature or throwing an error if present would also work, leaving the challenge of signing it to other tools. If you like, I could submit a pull request for either of those two.

**Comment by jet2jet** [comment]
Throwing an error is simple to implement, so I created PR #10 and merged.

I'm also considering to implement the feature 'removing the signature', but I think the feature should not be enabled by default, so I want to make some restrictions for it (such as an additional parameter or else).

If PR #10 satisfies you, please close this issue; if you want to wait for the feature 'removing the signature', keeping this issue open is no problem.

**Comment by AlexanderOMara** [comment]
Throwing an error works for me, I can strip the code signature out easily enough with some scripting.

Any chance of the latest updates being published to NPM? I'd really like to use this library instead of rcedit, but need the other changes.

**Comment by jet2jet** [comment]
> Any chance of the latest updates being published to NPM?

Sorry to be late. (I updated dependency packages and added linters/formatters for this project.)  
I just published package as `0.3.0`, so please use it.
